# Generated by Django 6.0.7 on 2026-08-18 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0007_comment_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='post',
        ),
    ]
