# Generated by Django 6.0.7 on 2026-08-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0010_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/%Y/%m/%d/'),
        ),
    ]
